name: Myles Braithwaite
favicon: null
layout_spectrum: 0.16407107189297676
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#25a5d4'
    - '#eda034'
    - '#3f504c'
    - '#ff5173'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
